### PR TITLE
Added Privacy Manifests for iOS and MacOS

### PR DESCRIPTION
**Pull request by martin-headspace**
> *Help Wanted*: Not sure if `sqflite_ios_privacy` is the right name for the Bundle
# What Changed
Added Privacy Manifests for iOS and macOS in preparation for the May 1st Deadline

# Sources
https://developer.apple.com/news/?id=3d8a9yyh
https://developer.apple.com/support/third-party-SDK-requirements/

### CODE REVIEW

**Comment by davidmartos96** [comment]
@martin-headspace Thank you!
Last week I've already updated the repo with the privacy manifest as well as with the latest version of sqlcipher, but I haven't had the chance to test it in a real ios/macos device.
I'd appreciate it if you can test the example app in the repo on an iOS device before we release a new version on pub.dev.

**Comment by davidmartos96** [comment]
@martin-headspace Another thing from this new update is that theoretically fmdb_override is not needed anymore if using the latest version of sqflite.
But again, I haven't found the time to test it on iOS/macOS

**Comment by martin-headspace** [comment]
What you are recommending is to use the `master` branch going forward?

**Comment by martin-headspace** [comment]
@davidmartos96 just tested on an:
- iPhone (iPhone 15 Pro)
- iPad (iPad Pro 3rd Gen)
- Mac (M1 Pro, 2021-)
And it worked just fine with my app

**Comment by davidmartos96** [comment]
> What you are recommending is to use the `master` branch going forward? 

The thing is that fmdb is not used anymore by sqflite, so it's not necessary to add the dependency_override section in the pubspec for sqflite, you can use regular sqflite version.

Thank you for testing!

**Comment by martin-headspace** [comment]
Awesome, thanks @davidmartos96 ! Do you know when we can expect a new version with the privacy manifest to become available?

**Comment by davidmartos96** [comment]
@martin-headspace Probably in the next few days. Just know that you can depend on the latest commit before waiting for an official release if you need to by using a git dependency in the pubspec

**Pull request closed without merging**
