### PR TITLE
Fix crash when normal sqflite is being used

### PR DESCRIPTION
**Pull request by daohoangson**
Related to #19.

After #31 is merged, we can switch back the URL for `fmdb_override` in pubspec.

### CODE REVIEW

**Comment by davidmartos96** [comment]
@daohoangson Oh thanks a lot for the contribution! I'll try to give this a try later and merge it :smile:

**Comment by davidmartos96** [comment]
@daohoangson Is the renaming necessary? Or is it just to avoid a warning?
If it is not really necessary I think leaving the original name would be better because merges from upstream sqflite would be easier.

**Comment by daohoangson** [comment]
The behavior is undefined when two methods have the same signature so I think we should rename.

The example works without the rename though. It's your call, I can revert the rename if you want.

**Comment by davidmartos96** [comment]
Thanks for explaining. 
It would be better to keep the rename then. Just in case.

**Comment by davidmartos96** [comment]
@daohoangson Sorry for the delay. I didn't have access to a macOS until now. All it's working perfectly. Thanks again for the contribution!!

**Pull request merged**
